title: Nagymaros
description: Jekyll theme for a conference website
baseurl: ""
url: https://yi-jie-zhou.github.io

permalink: pretty

include:
  - assets

home: /
copyright: Place Holder
indexing: true

exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

  
